version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
    restart: unless-stopped
    networks:
      - llama-network

networks:
  llama-network:
    driver: bridge
